---
title: "2.1-Taxonomic-Composition"
author: "Nathan WIlliams"
date: "2024-11-04"
output: html_document
---

```{r Libraries}
# Load necessary libraries
library(tidyverse)
```

```{r Import Data}
setwd("~/Dropbox/USC/Projects/grump.data/04-Data/version-1.3/")
grump_asv_long <- read_csv("grump_asv_long_version-1.3.1.csv")
```

```{r, echo=FALSE, fig1, fig.height = 10, fig.width = 15}
# Load necessary libraries
library(tidyverse)
library(patchwork)

# Filter data for Prokaryotes and calculate cumulative relative abundance
Prokaryotes <- grump_asv_long %>% filter(Level_1 == "Prokaryotes")

Prokaryotes_summary_Abundance <- Prokaryotes %>%
  group_by(Level_2, Eco_relevant_plank_groups) %>%
  summarise(Cumulative_Relative_Abundance = sum(Relative_Abundance, na.rm = TRUE))

# Define specific Level_2 order for Prokaryotes
level_2_order_prokaryotes <- c("Alphaproteobacteria", "Archaea", "Bacteroidota", "Cyanobacteria", "Gammaproteobacteria", "Other_Bacteria")

Prokaryotes_summary_Abundance <- Prokaryotes_summary_Abundance %>%
  mutate(Level_2 = factor(Level_2, levels = level_2_order_prokaryotes)) %>%
  arrange(Level_2)

# Prokaryotes plot with specific ylim ranges
Prokaryotes_plot <- ggplot(Prokaryotes_summary_Abundance, aes(x = Eco_relevant_plank_groups, y = Cumulative_Relative_Abundance, fill = Level_2)) +
  geom_bar(stat = "identity", colour = "black", size = 0.5) +
  facet_wrap(~ Level_2, scales = "free_x", nrow = 1) +
  scale_fill_manual(values = c("Alphaproteobacteria" = "#8DD3C7", "Archaea" = "#FFFFB3", "Bacteroidota" = "#BEBADA", 
                               "Cyanobacteria" = "#FB8072", "Gammaproteobacteria" = "#80B1D3", "Other_Bacteria" = "#FDB462")) +
  coord_cartesian(ylim = c(0, 150)) +
  theme_minimal() +
  labs(y = "Cumulative Relative Abundance", x = "") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 1, size = 12), strip.text = element_blank())

# Filter data for Eukaryotes and calculate cumulative relative abundance
Eukaryotes <- grump_asv_long %>% filter(Level_1 == "Eukaryotes")

Eukaryotes_summary_Abundance <- Eukaryotes %>%
  group_by(Level_2, Eco_relevant_plank_groups) %>%
   summarise(Cumulative_Relative_Abundance = sum(Relative_Abundance, na.rm = TRUE))

# Define specific Level_2 order for Eukaryotes
level_2_order_eukaryotes <- c("Chloroplast_16S", "Phytoplankton_18S", "Alveolata_Dinophyceae_18S",
                              "Other_Alveolata_18S", "Metazoa_18S", "Rhizaria_18S", "Other_Eukaryote_18S")

Eukaryotes_summary_Abundance <- Eukaryotes_summary_Abundance %>%
  mutate(Level_2 = factor(Level_2, levels = level_2_order_eukaryotes)) %>%
  arrange(Level_2)

# Eukaryotes plot with specific ylim ranges
Eukaryotes_plot <- ggplot(Eukaryotes_summary_Abundance, aes(x = Eco_relevant_plank_groups, y = Cumulative_Relative_Abundance, fill = Level_2)) +
  geom_bar(stat = "identity", colour = "black", size = 0.5) +
  facet_wrap(~ Level_2, scales = "free_x", nrow = 1) +
  scale_fill_manual(values = c("Chloroplast_16S" = "#f0909f", "Phytoplankton_18S" = "#ffdda0", 
                               "Alveolata_Dinophyceae_18S" = "#b8ab82", "Other_Alveolata_18S" = "#b5bf74", 
                               "Metazoa_18S" = "#a3fbff", "Rhizaria_18S" = "#ffd8fa", "Other_Eukaryote_18S" = "#bfa3ba")) +
  coord_cartesian(ylim = c(0, 50)) +
  theme_minimal() +
  labs(y = "Cumulative Relative Abundance", x = "Ecologically relevant plankton group") +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 1, size = 12))


Combined_plot <- Eukaryotes_plot / Prokaryotes_plot
Combined_plot
# Save the final plot
#setwd("~/Dropbox/USC/Projects/Project-1-data-release/02-Figures/")
#ggsave("DNA-adjusted-eco-groups.pdf", plot = Combined_plot, width = 11.7, height = 8.3)
```